# Generated by Django 2.1.1 on 2019-01-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidaextra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='hora',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.CharField(max_length=50),
        ),
    ]
